"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { store } from "./redux/store";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="px-20">
        {/* <Providers>
          <Navbar />
          {children}
        </Providers> */}
        <Provider store={store}>
          <Navbar />
          <ToastContainer autoClose={3000} />
          {children}
        </Provider>
      </body>
    </html>
  );
}
